## 1. Import Dependencies

In [1]:
!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116


In [1]:
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os

http://www.atarimania.com/roms/Roms.rar

In [ ]:
!python -m atari_py.import_roms .\ROMS

In [4]:
#!conda install -c conda-forge atari_py

In [2]:
environment_name = 'Breakout-v0'
env = gym.make(environment_name)

In [10]:
env.reset()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [11]:
env.action_space

Discrete(4)

In [12]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [13]:
episodes = 20
for episode in range(1,episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score += reward
    print (f"Episode : {episode} Score : {score}")
env.close()

Episode : 1 Score : 0.0
Episode : 2 Score : 0.0
Episode : 3 Score : 0.0
Episode : 4 Score : 0.0
Episode : 5 Score : 1.0
Episode : 6 Score : 2.0
Episode : 7 Score : 2.0
Episode : 8 Score : 1.0
Episode : 9 Score : 1.0
Episode : 10 Score : 3.0
Episode : 11 Score : 1.0
Episode : 12 Score : 2.0
Episode : 13 Score : 0.0
Episode : 14 Score : 5.0
Episode : 15 Score : 1.0
Episode : 16 Score : 0.0
Episode : 17 Score : 0.0
Episode : 18 Score : 4.0
Episode : 19 Score : 3.0
Episode : 20 Score : 4.0


## 3. Vectorise Environment and Train Model

In [22]:
env  = make_atari_env('Breakout-v0', n_envs=4, seed =0)
env = VecFrameStack(env, n_stack = 4)

In [36]:
log_path = os.path.join('Training','Logs')
model = A2C('CnnPolicy', env, verbose = 1, tensorboard_log = log_path, device='cuda')

Using cuda device
Wrapping the env in a VecTransposeImage.


In [37]:
model.learn(total_timesteps=300000)

Logging to Training\Logs\A2C_2
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 303      |
|    ep_rew_mean        | 2.12     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 100      |
|    time_elapsed       | 3        |
|    total_timesteps    | 500      |
| train/                |          |
|    entropy_loss       | -1.39    |
|    explained_variance | -1.19    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | -0.00929 |
|    value_loss         | 5.59e-05 |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 280      |
|    ep_rew_mean        | 1.61     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 200      |
|    time_elapsed       | 6        |
|    total_timesteps    | 1000     |
| train

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 278      |
|    ep_rew_mean        | 1.46     |
| time/                 |          |
|    fps                | 144      |
|    iterations         | 1400     |
|    time_elapsed       | 48       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -1.27    |
|    explained_variance | -240     |
|    learning_rate      | 0.0007   |
|    n_updates          | 1399     |
|    policy_loss        | 0.0343   |
|    value_loss         | 0.017    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 273      |
|    ep_rew_mean        | 1.38     |
| time/                 |          |
|    fps                | 140      |
|    iterations         | 1500     |
|    time_elapsed       | 53       |
|    total_timesteps    | 7500     |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 317      |
|    ep_rew_mean        | 2.22     |
| time/                 |          |
|    fps                | 125      |
|    iterations         | 2700     |
|    time_elapsed       | 107      |
|    total_timesteps    | 13500    |
| train/                |          |
|    entropy_loss       | -1.38    |
|    explained_variance | 0.641    |
|    learning_rate      | 0.0007   |
|    n_updates          | 2699     |
|    policy_loss        | -0.0403  |
|    value_loss         | 0.00106  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 315      |
|    ep_rew_mean        | 2.18     |
| time/                 |          |
|    fps                | 125      |
|    iterations         | 2800     |
|    time_elapsed       | 111      |
|    total_timesteps    | 14000    |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 347      |
|    ep_rew_mean        | 2.79     |
| time/                 |          |
|    fps                | 129      |
|    iterations         | 4000     |
|    time_elapsed       | 154      |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -0.577   |
|    explained_variance | -14.9    |
|    learning_rate      | 0.0007   |
|    n_updates          | 3999     |
|    policy_loss        | -0.0587  |
|    value_loss         | 0.0306   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 343       |
|    ep_rew_mean        | 2.76      |
| time/                 |           |
|    fps                | 130       |
|    iterations         | 4100      |
|    time_elapsed       | 157       |
|    total_timesteps    | 20500     |
| train/                |    

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 390      |
|    ep_rew_mean        | 3.85     |
| time/                 |          |
|    fps                | 131      |
|    iterations         | 5300     |
|    time_elapsed       | 201      |
|    total_timesteps    | 26500    |
| train/                |          |
|    entropy_loss       | -1.06    |
|    explained_variance | -93      |
|    learning_rate      | 0.0007   |
|    n_updates          | 5299     |
|    policy_loss        | -0.106   |
|    value_loss         | 0.0428   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 394      |
|    ep_rew_mean        | 3.96     |
| time/                 |          |
|    fps                | 132      |
|    iterations         | 5400     |
|    time_elapsed       | 204      |
|    total_timesteps    | 27000    |
| train/                |          |
|

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 414       |
|    ep_rew_mean        | 4.55      |
| time/                 |           |
|    fps                | 135       |
|    iterations         | 6700      |
|    time_elapsed       | 247       |
|    total_timesteps    | 33500     |
| train/                |           |
|    entropy_loss       | -0.468    |
|    explained_variance | -7.83e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 6699      |
|    policy_loss        | 0.00588   |
|    value_loss         | 0.00143   |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 412      |
|    ep_rew_mean        | 4.48     |
| time/                 |          |
|    fps                | 135      |
|    iterations         | 6800     |
|    time_elapsed       | 251      |
|    total_timesteps    | 34000    |
| train/             

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 403       |
|    ep_rew_mean        | 4.46      |
| time/                 |           |
|    fps                | 136       |
|    iterations         | 8000      |
|    time_elapsed       | 292       |
|    total_timesteps    | 40000     |
| train/                |           |
|    entropy_loss       | -0.468    |
|    explained_variance | -4.02e+14 |
|    learning_rate      | 0.0007    |
|    n_updates          | 7999      |
|    policy_loss        | 0.00636   |
|    value_loss         | 0.0076    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 399      |
|    ep_rew_mean        | 4.36     |
| time/                 |          |
|    fps                | 136      |
|    iterations         | 8100     |
|    time_elapsed       | 295      |
|    total_timesteps    | 40500    |
| train/             

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 425       |
|    ep_rew_mean        | 4.81      |
| time/                 |           |
|    fps                | 138       |
|    iterations         | 9300      |
|    time_elapsed       | 335       |
|    total_timesteps    | 46500     |
| train/                |           |
|    entropy_loss       | -0.816    |
|    explained_variance | -6.16e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 9299      |
|    policy_loss        | -0.0522   |
|    value_loss         | 0.00939   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 425       |
|    ep_rew_mean        | 4.82      |
| time/                 |           |
|    fps                | 138       |
|    iterations         | 9400      |
|    time_elapsed       | 339       |
|    total_timesteps    | 47000     |
| train/    

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 434      |
|    ep_rew_mean        | 4.91     |
| time/                 |          |
|    fps                | 140      |
|    iterations         | 10600    |
|    time_elapsed       | 378      |
|    total_timesteps    | 53000    |
| train/                |          |
|    entropy_loss       | -0.784   |
|    explained_variance | 0.998    |
|    learning_rate      | 0.0007   |
|    n_updates          | 10599    |
|    policy_loss        | 0.00948  |
|    value_loss         | 0.00785  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 434      |
|    ep_rew_mean        | 4.92     |
| time/                 |          |
|    fps                | 140      |
|    iterations         | 10700    |
|    time_elapsed       | 381      |
|    total_timesteps    | 53500    |
| train/                |          |
|

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 425       |
|    ep_rew_mean        | 4.89      |
| time/                 |           |
|    fps                | 141       |
|    iterations         | 11900     |
|    time_elapsed       | 420       |
|    total_timesteps    | 59500     |
| train/                |           |
|    entropy_loss       | -1.24     |
|    explained_variance | -1.31e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 11899     |
|    policy_loss        | 0.0319    |
|    value_loss         | 0.00269   |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 426      |
|    ep_rew_mean        | 4.9      |
| time/                 |          |
|    fps                | 141      |
|    iterations         | 12000    |
|    time_elapsed       | 424      |
|    total_timesteps    | 60000    |
| train/             

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 444      |
|    ep_rew_mean        | 5.15     |
| time/                 |          |
|    fps                | 142      |
|    iterations         | 13200    |
|    time_elapsed       | 463      |
|    total_timesteps    | 66000    |
| train/                |          |
|    entropy_loss       | -0.924   |
|    explained_variance | -25.6    |
|    learning_rate      | 0.0007   |
|    n_updates          | 13199    |
|    policy_loss        | -0.0082  |
|    value_loss         | 0.00222  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 443      |
|    ep_rew_mean        | 5.08     |
| time/                 |          |
|    fps                | 142      |
|    iterations         | 13300    |
|    time_elapsed       | 467      |
|    total_timesteps    | 66500    |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 428      |
|    ep_rew_mean        | 4.82     |
| time/                 |          |
|    fps                | 143      |
|    iterations         | 14500    |
|    time_elapsed       | 506      |
|    total_timesteps    | 72500    |
| train/                |          |
|    entropy_loss       | -1.24    |
|    explained_variance | 0.95     |
|    learning_rate      | 0.0007   |
|    n_updates          | 14499    |
|    policy_loss        | -0.092   |
|    value_loss         | 0.0218   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 421      |
|    ep_rew_mean        | 4.69     |
| time/                 |          |
|    fps                | 143      |
|    iterations         | 14600    |
|    time_elapsed       | 510      |
|    total_timesteps    | 73000    |
| train/                |          |
|

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 410       |
|    ep_rew_mean        | 4.54      |
| time/                 |           |
|    fps                | 143       |
|    iterations         | 15800     |
|    time_elapsed       | 550       |
|    total_timesteps    | 79000     |
| train/                |           |
|    entropy_loss       | -0.791    |
|    explained_variance | -2.66e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 15799     |
|    policy_loss        | 0.084     |
|    value_loss         | 0.0255    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 413       |
|    ep_rew_mean        | 4.59      |
| time/                 |           |
|    fps                | 143       |
|    iterations         | 15900     |
|    time_elapsed       | 553       |
|    total_timesteps    | 79500     |
| train/    

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 443      |
|    ep_rew_mean        | 5.24     |
| time/                 |          |
|    fps                | 144      |
|    iterations         | 17100    |
|    time_elapsed       | 593      |
|    total_timesteps    | 85500    |
| train/                |          |
|    entropy_loss       | -0.681   |
|    explained_variance | -144     |
|    learning_rate      | 0.0007   |
|    n_updates          | 17099    |
|    policy_loss        | -0.144   |
|    value_loss         | 0.0794   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 447      |
|    ep_rew_mean        | 5.34     |
| time/                 |          |
|    fps                | 144      |
|    iterations         | 17200    |
|    time_elapsed       | 596      |
|    total_timesteps    | 86000    |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 472      |
|    ep_rew_mean        | 5.66     |
| time/                 |          |
|    fps                | 144      |
|    iterations         | 18400    |
|    time_elapsed       | 636      |
|    total_timesteps    | 92000    |
| train/                |          |
|    entropy_loss       | -0.47    |
|    explained_variance | 0.13     |
|    learning_rate      | 0.0007   |
|    n_updates          | 18399    |
|    policy_loss        | -0.234   |
|    value_loss         | 0.0226   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 472      |
|    ep_rew_mean        | 5.62     |
| time/                 |          |
|    fps                | 144      |
|    iterations         | 18500    |
|    time_elapsed       | 639      |
|    total_timesteps    | 92500    |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 486      |
|    ep_rew_mean        | 5.84     |
| time/                 |          |
|    fps                | 145      |
|    iterations         | 19700    |
|    time_elapsed       | 678      |
|    total_timesteps    | 98500    |
| train/                |          |
|    entropy_loss       | -0.779   |
|    explained_variance | -28.1    |
|    learning_rate      | 0.0007   |
|    n_updates          | 19699    |
|    policy_loss        | -0.0572  |
|    value_loss         | 0.0188   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 487      |
|    ep_rew_mean        | 5.89     |
| time/                 |          |
|    fps                | 145      |
|    iterations         | 19800    |
|    time_elapsed       | 682      |
|    total_timesteps    | 99000    |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 472      |
|    ep_rew_mean        | 5.65     |
| time/                 |          |
|    fps                | 145      |
|    iterations         | 21000    |
|    time_elapsed       | 721      |
|    total_timesteps    | 105000   |
| train/                |          |
|    entropy_loss       | -0.374   |
|    explained_variance | -18.4    |
|    learning_rate      | 0.0007   |
|    n_updates          | 20999    |
|    policy_loss        | -0.138   |
|    value_loss         | 0.105    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 473      |
|    ep_rew_mean        | 5.69     |
| time/                 |          |
|    fps                | 145      |
|    iterations         | 21100    |
|    time_elapsed       | 724      |
|    total_timesteps    | 105500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 469      |
|    ep_rew_mean        | 5.76     |
| time/                 |          |
|    fps                | 145      |
|    iterations         | 22300    |
|    time_elapsed       | 764      |
|    total_timesteps    | 111500   |
| train/                |          |
|    entropy_loss       | -0.374   |
|    explained_variance | 0.886    |
|    learning_rate      | 0.0007   |
|    n_updates          | 22299    |
|    policy_loss        | 0.0766   |
|    value_loss         | 0.0541   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 467      |
|    ep_rew_mean        | 5.77     |
| time/                 |          |
|    fps                | 145      |
|    iterations         | 22400    |
|    time_elapsed       | 767      |
|    total_timesteps    | 112000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 450      |
|    ep_rew_mean        | 5.35     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 23600    |
|    time_elapsed       | 806      |
|    total_timesteps    | 118000   |
| train/                |          |
|    entropy_loss       | -0.55    |
|    explained_variance | 0.747    |
|    learning_rate      | 0.0007   |
|    n_updates          | 23599    |
|    policy_loss        | -0.0268  |
|    value_loss         | 0.00102  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 450      |
|    ep_rew_mean        | 5.34     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 23700    |
|    time_elapsed       | 810      |
|    total_timesteps    | 118500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 446      |
|    ep_rew_mean        | 5.24     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 24900    |
|    time_elapsed       | 849      |
|    total_timesteps    | 124500   |
| train/                |          |
|    entropy_loss       | -0.835   |
|    explained_variance | 0.821    |
|    learning_rate      | 0.0007   |
|    n_updates          | 24899    |
|    policy_loss        | 0.0822   |
|    value_loss         | 0.0796   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 444      |
|    ep_rew_mean        | 5.17     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 25000    |
|    time_elapsed       | 852      |
|    total_timesteps    | 125000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 424      |
|    ep_rew_mean        | 4.75     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 26200    |
|    time_elapsed       | 892      |
|    total_timesteps    | 131000   |
| train/                |          |
|    entropy_loss       | -0.679   |
|    explained_variance | -0.411   |
|    learning_rate      | 0.0007   |
|    n_updates          | 26199    |
|    policy_loss        | -0.068   |
|    value_loss         | 0.0067   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 424      |
|    ep_rew_mean        | 4.76     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 26300    |
|    time_elapsed       | 895      |
|    total_timesteps    | 131500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 448      |
|    ep_rew_mean        | 5.22     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 27500    |
|    time_elapsed       | 935      |
|    total_timesteps    | 137500   |
| train/                |          |
|    entropy_loss       | -0.622   |
|    explained_variance | 0.774    |
|    learning_rate      | 0.0007   |
|    n_updates          | 27499    |
|    policy_loss        | -0.011   |
|    value_loss         | 0.0769   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 457      |
|    ep_rew_mean        | 5.42     |
| time/                 |          |
|    fps                | 146      |
|    iterations         | 27600    |
|    time_elapsed       | 939      |
|    total_timesteps    | 138000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 497      |
|    ep_rew_mean        | 6.21     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 28800    |
|    time_elapsed       | 978      |
|    total_timesteps    | 144000   |
| train/                |          |
|    entropy_loss       | -0.725   |
|    explained_variance | -696     |
|    learning_rate      | 0.0007   |
|    n_updates          | 28799    |
|    policy_loss        | 0.0828   |
|    value_loss         | 0.0181   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 504       |
|    ep_rew_mean        | 6.37      |
| time/                 |           |
|    fps                | 147       |
|    iterations         | 28900     |
|    time_elapsed       | 982       |
|    total_timesteps    | 144500    |
| train/                |    

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 518       |
|    ep_rew_mean        | 6.59      |
| time/                 |           |
|    fps                | 147       |
|    iterations         | 30100     |
|    time_elapsed       | 1022      |
|    total_timesteps    | 150500    |
| train/                |           |
|    entropy_loss       | -0.00506  |
|    explained_variance | -81.8     |
|    learning_rate      | 0.0007    |
|    n_updates          | 30099     |
|    policy_loss        | -0.000165 |
|    value_loss         | 0.228     |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 516      |
|    ep_rew_mean        | 6.56     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 30200    |
|    time_elapsed       | 1025     |
|    total_timesteps    | 151000   |
| train/             

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 520      |
|    ep_rew_mean        | 6.69     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 31400    |
|    time_elapsed       | 1065     |
|    total_timesteps    | 157000   |
| train/                |          |
|    entropy_loss       | -0.897   |
|    explained_variance | 0.199    |
|    learning_rate      | 0.0007   |
|    n_updates          | 31399    |
|    policy_loss        | -0.0816  |
|    value_loss         | 0.0861   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 523      |
|    ep_rew_mean        | 6.74     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 31500    |
|    time_elapsed       | 1068     |
|    total_timesteps    | 157500   |
| train/                |          |
|

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 514       |
|    ep_rew_mean        | 6.6       |
| time/                 |           |
|    fps                | 147       |
|    iterations         | 32800     |
|    time_elapsed       | 1111      |
|    total_timesteps    | 164000    |
| train/                |           |
|    entropy_loss       | -0.745    |
|    explained_variance | -6.74e+14 |
|    learning_rate      | 0.0007    |
|    n_updates          | 32799     |
|    policy_loss        | 0.0437    |
|    value_loss         | 0.0223    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 514      |
|    ep_rew_mean        | 6.59     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 32900    |
|    time_elapsed       | 1115     |
|    total_timesteps    | 164500   |
| train/             

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 482       |
|    ep_rew_mean        | 5.94      |
| time/                 |           |
|    fps                | 147       |
|    iterations         | 34100     |
|    time_elapsed       | 1155      |
|    total_timesteps    | 170500    |
| train/                |           |
|    entropy_loss       | -0.876    |
|    explained_variance | -3.46e+06 |
|    learning_rate      | 0.0007    |
|    n_updates          | 34099     |
|    policy_loss        | -0.0717   |
|    value_loss         | 0.0273    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 475      |
|    ep_rew_mean        | 5.76     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 34200    |
|    time_elapsed       | 1158     |
|    total_timesteps    | 171000   |
| train/             

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 469       |
|    ep_rew_mean        | 5.68      |
| time/                 |           |
|    fps                | 147       |
|    iterations         | 35400     |
|    time_elapsed       | 1198      |
|    total_timesteps    | 177000    |
| train/                |           |
|    entropy_loss       | -0.00147  |
|    explained_variance | -7.81     |
|    learning_rate      | 0.0007    |
|    n_updates          | 35399     |
|    policy_loss        | -4.36e-05 |
|    value_loss         | 0.169     |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 474      |
|    ep_rew_mean        | 5.79     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 35500    |
|    time_elapsed       | 1201     |
|    total_timesteps    | 177500   |
| train/             

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 499      |
|    ep_rew_mean        | 6.2      |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 36700    |
|    time_elapsed       | 1241     |
|    total_timesteps    | 183500   |
| train/                |          |
|    entropy_loss       | -0.265   |
|    explained_variance | -80.2    |
|    learning_rate      | 0.0007   |
|    n_updates          | 36699    |
|    policy_loss        | -0.0287  |
|    value_loss         | 0.0363   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 498      |
|    ep_rew_mean        | 6.24     |
| time/                 |          |
|    fps                | 147      |
|    iterations         | 36800    |
|    time_elapsed       | 1244     |
|    total_timesteps    | 184000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 500      |
|    ep_rew_mean        | 6.35     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 38000    |
|    time_elapsed       | 1282     |
|    total_timesteps    | 190000   |
| train/                |          |
|    entropy_loss       | -0.0403  |
|    explained_variance | -58.8    |
|    learning_rate      | 0.0007   |
|    n_updates          | 37999    |
|    policy_loss        | -0.00102 |
|    value_loss         | 0.152    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 499      |
|    ep_rew_mean        | 6.35     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 38100    |
|    time_elapsed       | 1285     |
|    total_timesteps    | 190500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 536      |
|    ep_rew_mean        | 6.97     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 39400    |
|    time_elapsed       | 1326     |
|    total_timesteps    | 197000   |
| train/                |          |
|    entropy_loss       | -0.476   |
|    explained_variance | 0.788    |
|    learning_rate      | 0.0007   |
|    n_updates          | 39399    |
|    policy_loss        | 0.00661  |
|    value_loss         | 0.048    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 539      |
|    ep_rew_mean        | 7.03     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 39500    |
|    time_elapsed       | 1329     |
|    total_timesteps    | 197500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 516      |
|    ep_rew_mean        | 6.58     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 40700    |
|    time_elapsed       | 1368     |
|    total_timesteps    | 203500   |
| train/                |          |
|    entropy_loss       | -0.248   |
|    explained_variance | -131     |
|    learning_rate      | 0.0007   |
|    n_updates          | 40699    |
|    policy_loss        | 0.0151   |
|    value_loss         | 0.028    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 514      |
|    ep_rew_mean        | 6.52     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 40800    |
|    time_elapsed       | 1371     |
|    total_timesteps    | 204000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 519      |
|    ep_rew_mean        | 6.68     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 42000    |
|    time_elapsed       | 1409     |
|    total_timesteps    | 210000   |
| train/                |          |
|    entropy_loss       | -0.0744  |
|    explained_variance | -8.63    |
|    learning_rate      | 0.0007   |
|    n_updates          | 41999    |
|    policy_loss        | -0.00293 |
|    value_loss         | 0.0389   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 522      |
|    ep_rew_mean        | 6.77     |
| time/                 |          |
|    fps                | 148      |
|    iterations         | 42100    |
|    time_elapsed       | 1412     |
|    total_timesteps    | 210500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 549      |
|    ep_rew_mean        | 7.36     |
| time/                 |          |
|    fps                | 149      |
|    iterations         | 43300    |
|    time_elapsed       | 1450     |
|    total_timesteps    | 216500   |
| train/                |          |
|    entropy_loss       | -0.144   |
|    explained_variance | -556     |
|    learning_rate      | 0.0007   |
|    n_updates          | 43299    |
|    policy_loss        | 0.00806  |
|    value_loss         | 0.203    |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 559       |
|    ep_rew_mean        | 7.65      |
| time/                 |           |
|    fps                | 149       |
|    iterations         | 43400     |
|    time_elapsed       | 1454      |
|    total_timesteps    | 217000    |
| train/                |    

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 572      |
|    ep_rew_mean        | 8.01     |
| time/                 |          |
|    fps                | 149      |
|    iterations         | 44600    |
|    time_elapsed       | 1491     |
|    total_timesteps    | 223000   |
| train/                |          |
|    entropy_loss       | -0.0586  |
|    explained_variance | 0.176    |
|    learning_rate      | 0.0007   |
|    n_updates          | 44599    |
|    policy_loss        | -0.00201 |
|    value_loss         | 0.274    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 576      |
|    ep_rew_mean        | 8.12     |
| time/                 |          |
|    fps                | 149      |
|    iterations         | 44700    |
|    time_elapsed       | 1494     |
|    total_timesteps    | 223500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 578      |
|    ep_rew_mean        | 8.03     |
| time/                 |          |
|    fps                | 149      |
|    iterations         | 46000    |
|    time_elapsed       | 1535     |
|    total_timesteps    | 230000   |
| train/                |          |
|    entropy_loss       | -0.8     |
|    explained_variance | nan      |
|    learning_rate      | 0.0007   |
|    n_updates          | 45999    |
|    policy_loss        | -0.181   |
|    value_loss         | 0.165    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 572      |
|    ep_rew_mean        | 7.92     |
| time/                 |          |
|    fps                | 149      |
|    iterations         | 46100    |
|    time_elapsed       | 1538     |
|    total_timesteps    | 230500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 562      |
|    ep_rew_mean        | 7.58     |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 47300    |
|    time_elapsed       | 1575     |
|    total_timesteps    | 236500   |
| train/                |          |
|    entropy_loss       | -0.175   |
|    explained_variance | -75.8    |
|    learning_rate      | 0.0007   |
|    n_updates          | 47299    |
|    policy_loss        | -0.0227  |
|    value_loss         | 0.0165   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 560      |
|    ep_rew_mean        | 7.54     |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 47400    |
|    time_elapsed       | 1578     |
|    total_timesteps    | 237000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 584      |
|    ep_rew_mean        | 8.3      |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 48600    |
|    time_elapsed       | 1616     |
|    total_timesteps    | 243000   |
| train/                |          |
|    entropy_loss       | -0.465   |
|    explained_variance | 0.781    |
|    learning_rate      | 0.0007   |
|    n_updates          | 48599    |
|    policy_loss        | -0.0624  |
|    value_loss         | 0.0875   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 589      |
|    ep_rew_mean        | 8.39     |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 48700    |
|    time_elapsed       | 1619     |
|    total_timesteps    | 243500   |
| train/                |          |
|

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 573       |
|    ep_rew_mean        | 8.06      |
| time/                 |           |
|    fps                | 150       |
|    iterations         | 49900     |
|    time_elapsed       | 1658      |
|    total_timesteps    | 249500    |
| train/                |           |
|    entropy_loss       | -0.397    |
|    explained_variance | -9.18e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 49899     |
|    policy_loss        | -0.0643   |
|    value_loss         | 0.0323    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 562       |
|    ep_rew_mean        | 7.86      |
| time/                 |           |
|    fps                | 150       |
|    iterations         | 50000     |
|    time_elapsed       | 1661      |
|    total_timesteps    | 250000    |
| train/    

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 536      |
|    ep_rew_mean        | 7        |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 51200    |
|    time_elapsed       | 1698     |
|    total_timesteps    | 256000   |
| train/                |          |
|    entropy_loss       | -0.454   |
|    explained_variance | 0.846    |
|    learning_rate      | 0.0007   |
|    n_updates          | 51199    |
|    policy_loss        | -0.0689  |
|    value_loss         | 0.025    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 527      |
|    ep_rew_mean        | 6.84     |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 51300    |
|    time_elapsed       | 1702     |
|    total_timesteps    | 256500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 550      |
|    ep_rew_mean        | 7.59     |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 52500    |
|    time_elapsed       | 1739     |
|    total_timesteps    | 262500   |
| train/                |          |
|    entropy_loss       | -0.104   |
|    explained_variance | -18.4    |
|    learning_rate      | 0.0007   |
|    n_updates          | 52499    |
|    policy_loss        | 0.00245  |
|    value_loss         | 0.0293   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 547      |
|    ep_rew_mean        | 7.56     |
| time/                 |          |
|    fps                | 150      |
|    iterations         | 52600    |
|    time_elapsed       | 1742     |
|    total_timesteps    | 263000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 574      |
|    ep_rew_mean        | 8.3      |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 53800    |
|    time_elapsed       | 1780     |
|    total_timesteps    | 269000   |
| train/                |          |
|    entropy_loss       | -0.00465 |
|    explained_variance | 0.949    |
|    learning_rate      | 0.0007   |
|    n_updates          | 53799    |
|    policy_loss        | 8.35e-05 |
|    value_loss         | 0.0135   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 575      |
|    ep_rew_mean        | 8.29     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 53900    |
|    time_elapsed       | 1783     |
|    total_timesteps    | 269500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 586      |
|    ep_rew_mean        | 8.37     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 55100    |
|    time_elapsed       | 1821     |
|    total_timesteps    | 275500   |
| train/                |          |
|    entropy_loss       | -0.332   |
|    explained_variance | 0.749    |
|    learning_rate      | 0.0007   |
|    n_updates          | 55099    |
|    policy_loss        | -0.0743  |
|    value_loss         | 0.0358   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 587       |
|    ep_rew_mean        | 8.38      |
| time/                 |           |
|    fps                | 151       |
|    iterations         | 55200     |
|    time_elapsed       | 1824      |
|    total_timesteps    | 276000    |
| train/                |    

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 587      |
|    ep_rew_mean        | 8.48     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 56400    |
|    time_elapsed       | 1862     |
|    total_timesteps    | 282000   |
| train/                |          |
|    entropy_loss       | -0.648   |
|    explained_variance | -389     |
|    learning_rate      | 0.0007   |
|    n_updates          | 56399    |
|    policy_loss        | 0.571    |
|    value_loss         | 1.22     |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 586      |
|    ep_rew_mean        | 8.52     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 56500    |
|    time_elapsed       | 1865     |
|    total_timesteps    | 282500   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 611      |
|    ep_rew_mean        | 8.91     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 57700    |
|    time_elapsed       | 1902     |
|    total_timesteps    | 288500   |
| train/                |          |
|    entropy_loss       | -0.729   |
|    explained_variance | -885     |
|    learning_rate      | 0.0007   |
|    n_updates          | 57699    |
|    policy_loss        | 0.137    |
|    value_loss         | 0.0373   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 612      |
|    ep_rew_mean        | 8.95     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 57800    |
|    time_elapsed       | 1906     |
|    total_timesteps    | 289000   |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 639      |
|    ep_rew_mean        | 9.44     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 59000    |
|    time_elapsed       | 1943     |
|    total_timesteps    | 295000   |
| train/                |          |
|    entropy_loss       | -0.00389 |
|    explained_variance | -25.7    |
|    learning_rate      | 0.0007   |
|    n_updates          | 58999    |
|    policy_loss        | 0.00018  |
|    value_loss         | 0.0658   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 634      |
|    ep_rew_mean        | 9.28     |
| time/                 |          |
|    fps                | 151      |
|    iterations         | 59100    |
|    time_elapsed       | 1946     |
|    total_timesteps    | 295500   |
| train/                |          |
|

### 4. Save and Reload Model

In [4]:
a2c_path = os.path.join('Training', 'Saved Models', 'A2C_300k_Model')

In [ ]:
model.save(a2c_path)

In [18]:
del model

In [8]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


### 5. Evaluate and Test

In [9]:
env  = make_atari_env('Breakout-v0', n_envs=1, seed =0)
env = VecFrameStack(env, n_stack = 4)

In [10]:
# env.render(mode = "human")

In [11]:
evaluate_policy(model, env, n_eval_episodes = 10, render=True)

D:\Program_Installation\anaconda\lib\site-packages\gym\envs\atari\environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(
D:\Program_Installation\anaconda\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


(11.1, 2.7367864366808017)

In [12]:
env.close()